phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18  
    commands:
      - echo Installing Java dependencies...
      - mvn install
      - echo Installing Node.js dependencies...
      - cd frontend && npm install  # Adjust directory if necessary

